ARG BASE_IMG
FROM user/cmsjson:base

MAINTAINER Sarun Nuntaviriyakul <sarun.nuntaviriyakul@cern.ch>
LABEL org.opencontainers.image.source https://github.com/guyzsarun/xrootd-cmsjson

RUN pip3 install pytest

COPY . .

RUN mkdir -p build
RUN cd build && cmake .. && make && make install